import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Netflix clone</title>
        <meta name="description" content="Generated by zx hahaha" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section></section>
      </main>
    </div>
  );
}
